version: '3'

services:
  users:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=users
    ports:
      - '5432:5432'

  news:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=news
    ports:
      - '5433:5432'
      
  minio:
    <<: *minio-common
    hostname: news-portal
    volumes:
      - data1-1:/data
    networks:
      - mainnetwork
    ports:
      - "9001:9001"